---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: A seção a seguir descreve os principais conceitos e termos usados no documento. 
---
= Principais conceitos e termos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seção a seguir descreve os principais conceitos e termos usados no documento.



=== Autoridade de certificação (CA)

A CA é uma entidade confiável que emite certificados SSL (Secure Sockets Layer).



=== Pilha dupla

Uma rede de pilha dupla é um ambiente de rede que suporta o uso simultâneo de endereços IPv4 e IPv6.



=== Alta disponibilidade (HA)

Os nós de cluster são configurados em pares de HA para operações sem interrupções.



=== Número de unidade lógica (LUN)

Um LUN é um número usado para identificar uma unidade lógica dentro de uma SAN (Storage Area Network). Esses dispositivos endereçáveis são normalmente discos lógicos acessados através do protocolo SCSI (Small Computer System Interface) ou de um de seus derivados encapsulados.



=== Gerenciador de ferramentas do ONTAP

O Gerenciador de ferramentas do ONTAP fornece mais controle às ferramentas do ONTAP para o administrador do VMware vSphere sobre as instâncias gerenciadas do vCenter Server e os back-ends de storage integrados. O ONTAP Tools Manager ajuda no gerenciamento de instâncias do vCenter Server, backends de armazenamento, certificados, senhas e downloads de pacotes de log.



=== Abrir dispositivo virtual (OVA)

O OVA é um padrão aberto para empacotar e distribuir dispositivos virtuais ou software que deve ser executado em máquinas virtuais.



=== SnapMirror ative (SMAS)

O SnapMirror active Sync permite que os serviços empresariais continuem operando mesmo em uma falha completa do local, com suporte ao failover de aplicações de forma transparente, usando uma cópia secundária. A intervenção manual nem o script personalizado são necessários para acionar um failover com a sincronização ativa do SnapMirror.



=== Adaptador de replicação de armazenamento (SRA)

O SRA é o software específico do fornecedor de storage instalado no dispositivo SRM. O adaptador permite a comunicação entre o Site Recovery Manager e uma controladora de storage no nível de Storage Virtual Machine (SVM) e a configuração no nível do cluster.



=== Máquina virtual de storage (SVM)

Como uma máquina virtual em execução em um hipervisor, a SVM é uma entidade lógica que abstrai recursos físicos. O SVM contém volumes de dados e uma ou mais LIFs por meio dos quais eles fornecem dados aos clientes.



=== Sistema de arquivos de máquina virtual (VMFS)

O VMFS é um sistema de arquivos em cluster projetado especificamente para armazenar arquivos de máquina virtual em ambientes VMware vSphere.



=== Volumes virtuais (vVols)

Os vVols fornecem uma abstração em nível de volume para armazenamento usado por uma máquina virtual. Ele inclui vários benefícios e fornece uma alternativa ao uso de um LUN tradicional. Um datastore da VVol é normalmente associado a um único LUN que atua como um contentor para os vVols.



=== Política de storage da VM

As políticas de armazenamento de VM são criadas no vCenter Server em políticas e perfis. Para vVols, crie um conjunto de regras usando regras do provedor do tipo de storage do NetApp vVols.



=== VMware Site Recovery Manager (SRM)

O SRM fornece continuidade dos negócios, recuperação de desastres, migração de sites e recursos de teste sem interrupções para ambientes virtuais VMware.



=== VMware vSphere APIs for Storage Awareness (VASA)

O VASA é um conjunto de APIs que integram storage arrays com o vCenter Server para gerenciamento e administração. A arquitetura é baseada em vários componentes, incluindo o provedor VASA, que lida com a comunicação entre o VMware vSphere e os sistemas de armazenamento.



=== VMware vSphere Storage APIs - Array Integration (VAAI)

O VAAI é um conjunto de APIs que permite a comunicação entre os hosts do VMware vSphere ESXi e os dispositivos de armazenamento. As APIs incluem um conjunto de operações primitivas usadas pelos hosts para descarregar operações de storage para o array. O VAAI pode fornecer melhorias significativas de desempenho para tarefas com uso intenso de storage.



=== Armazenamento de dados vVols

O datastore vVols é uma representação lógica do datastore de um contentor vVols que é criado e mantido por um provedor VASA.



=== RPO zero

RPO significa objetivo do ponto de restauração, que é a quantidade de perda de dados considerada aceitável durante um determinado tempo. Zero RPO significa que nenhuma perda de dados é aceitável.
