---
permalink: configure/verify-registration.html 
sidebar: sidebar 
keywords:  
summary: Verifique se o SVM integrado está listado em Fornecedor VASA da IU do cliente vCenter. 
---
= Verifique o provedor VASA registrado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique se o provedor VASA integrado está listado em Fornecedor VASA da IU do cliente vCenter e da IU do plug-in remoto.

*Passos*

. Para verificar o provedor VASA da IU do vCenter client, siga estas etapas:
+
.. Navegue até o vCenter Server.
.. Inicie sessão com as credenciais de administrador.
.. Selecione *fornecedores de armazenamento*.
.. Selecione *Configurar*.
.. Em Provedor de armazenamento/backends de armazenamento, verifique se o provedor VASA integrado está listado corretamente.


. Para verificar o fornecedor VASA a partir da IU do plug-in remoto, siga estes passos:
+
.. Faça login no cliente vSphere usando `\https://vcenterip/ui`
.. Na página de atalhos, clique em *Ferramentas do NetApp ONTAP* na seção plug-ins.
.. Pode ver o fornecedor VASA registado na página de descrição geral e na página *Definições* > *Definições do fornecedor VASA*.



